name: Demo CI Pipeline
on: [push]
jobs:
  test_app:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Start environment
        run:  docker-compose up -d
      - name: Wait for warmup
        run:  sleep 10
      - name: Initialize test db
        run:  docker exec demo-wordpress_wp-cli_1 wp db import /build/ci-db.sql
      - name: Test Site
        run:  curl --fail http://localhost | grep "Hello world"
